### ISSUE TITLE
能否把用jialezi/ss-with-net-speeder:latest部署的加上？

### ISSUE THREAD

**Issue by kirbyzhu** [malaohu/ssr-with-net-speeder#20]
lowid的好像部署不成功了

**Comment by malaohu** [comment]
部署不成功可以看看这篇文章介绍
http://51.ruyo.net/p/3597.html

能否把用jialezi/ss-with-net-speeder:latest部署的加上？ 是啥意思？

**Comment by kirbyzhu** [comment]
部署没问题了

我说的那个是malaohu/ssr-with-net-speeder-arukas 只能读取malaohu和lowid、smounives/shadowsocksr-docker部署的app，不能识别jialezi镜像。

另外如果有混淆协议等，在读取ip和端口生成的二维码的时候，在协议读取上有点问题，不能正确的读成参数，会在一行里面显示。

**Comment by malaohu** [comment]
关于二维码的问题请参考 #10 

目前jialezi的镜像不在清单里面。

**Comment by malaohu** [comment]
已经支持。[https://github.com/malaohu/ssr-with-net-speeder/commit/75d1261b63e90e75f747991bc6f5506f9e547172](url)
