### ISSUE TITLE
关于新的协议 auth_chain_a支持问题

### ISSUE THREAD

**Issue by wangwill** [malaohu/ssr-with-net-speeder#22]
部署时显示不支持新协议错误 如图
![image](https://cloud.githubusercontent.com/assets/9379983/26519461/6f6b9888-4300-11e7-8408-a7f272181bd6.png)

**Comment by wangwill** [comment]
是不是要等python版本支持？

**Comment by kirbyzhu** [comment]
还用老协议不就行了么

**Comment by wangwill** [comment]
是啊 我怎么没想到

**Comment by malaohu** [comment]
不支持新协议的
