### ISSUE TITLE
实时自动获取Arukas的Ip和Port的代码能否加上SSR最新的服务器订阅功能

### ISSUE THREAD

**Issue by msghost** [malaohu/ssr-with-net-speeder#24]
@malaohu 
HI，非常感谢你做了这么多实用的工具！
最近SSR推出了服务器节点数据的订阅功能，说明在这里：https://github.com/breakwa11/shadowsocks-rss/wiki/Subscribe-%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AE%A2%E9%98%85%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3
简单来说就是在客户端上配置一个地址，然后客户端去这个地址按相应格式取到服务器配置信息。
如果能修改一下当前的代码，似乎可以通过你的显示SSR信息的docker发布到Arukas的endpoint，然后让SSR客户端去取。

**Comment by msghost** [comment]
这样，Arukas不定期变更IP和端口的问题就解决了

**Comment by malaohu** [comment]
谢谢你的反馈。这个功能已经加上。
演示地址：http://arukas.somecolor.cc/ssr/subscribe/10

**Comment by malaohu** [comment]
http://51.ruyo.net/p/4217.html
