### ISSUE TITLE
这个被樱花封了么？

### ISSUE THREAD

**Issue by gujiangjiang** [malaohu/ssr-with-net-speeder#26]
已经无法正常创建了。。。

试了好几天了，都是失败，一直无法创建成功了。。。

**Comment by HunDunDM** [comment]
同问。。。

**Comment by zengjuyi** [comment]
是不是不可以搭建了

**Comment by malaohu** [comment]
@zengjuyi 哇，膜拜一下大佬。

**Comment by malaohu** [comment]
是能搭建的，只不过失败率非常高。
只能反复新建重启吧。。没有其他办法了。
http://51.ruyo.net/p/4331.html
