### ISSUE TITLE
节点ip端口自动更新面板设置全部完成出现无法找到ssr的提示

### ISSUE THREAD

**Issue by PPPss** [malaohu/ssr-with-net-speeder#5]
就是找不到我设置的app

**Comment by billysingo** [comment]
因为ssr的git地址变了。

**Comment by malaohu** [comment]
你的APP 镜像是啥？
将创建的命令发出来看看。

**Comment by PPPss** [comment]
ssr 用的是malaohu/ssr-with-net-speeder
展示app用的是malaohu/ssr-with-net-speeder-arukas
cmd 是node /app/server.js token a877a1d2-fabb-412e-b52d-26d5e6977 secret 6uj6uwfmEqewUKeLgQG87DAUHxp5CpnO9uzCgIhwad5W8TAcdCoOPokTtS8k 42ba1694-7e3a-4967-b75d-9e665302a35b
但是最后就出现【没有查询到数据。请检查node启动参数是否正确。更多内容请访问：https://github.com/malaohu/ssr-with-net-speeder/tree/arukas】
请帮忙检查一下错误

**Comment by malaohu** [comment]
node /app/server.js a877a1d2-fabb-412e-1234-26d5e6977 6uj6uwfmEqewUKeLgQG87DAUHxp5CpnO9uzCgIhwad5W8TAcdCoOPokTtS8k 42ba1694-7e3a-4967-b75d-9e61234a35b

将 token 和 secret  替换掉。。。

**Comment by PPPss** [comment]
Thanks~
