### ISSUE TITLE
演示網站失效 是否可用？

### ISSUE THREAD

**Issue by MV9KEz7nx6dx** [malaohu/ssr-with-net-speeder#7]
没有查询到数据。请检查node启动参数是否正确。更多内容请访问：https://github.com/malaohu/ssr-with-net-speeder/tree/arukas

還可以用嗎？

**Comment by hldh214** [comment]
api返回500错误, 不清楚是哪边的问题
{
  "status": "500",
  "error": "Internal Server Error"
}

**Comment by hldh214** [comment]
api返回500错误, 不清楚是哪边的问题
{
  "status": "500",
  "error": "Internal Server Error"
}

**Comment by MV9KEz7nx6dx** [comment]
ok 明了 還好有備份 謝謝

**Comment by hldh214** [comment]
https://github.com/arukasio/cli/issues/47
已修复

**Comment by MV9KEz7nx6dx** [comment]
大贊 新年快樂 鸡年大吉

**Comment by malaohu** [comment]
Good ~~
