### ISSUE TITLE
fork arukas分支生成的docker不能运行

### ISSUE THREAD

**Issue by liufanl** [malaohu/ssr-with-net-speeder#8]
fork arukas分支，然后在docker.com生成镜像，部署到arukas，出现Failed to start

**Comment by malaohu** [comment]
检查 CMD 参数。
直接使用我的镜像试一试。

**Comment by liufanl** [comment]
@malaohu 同样的参数，用你的镜像没有问题，用自己生成的就不行。

**Comment by malaohu** [comment]
你的镜像在hub.docker.com编译成功了么？

**Comment by liufanl** [comment]
@malaohu 编译成功了的

Building in Docker Cloud's infrastructure...
Cloning into '.'...

KernelVersion: 4.4.0-59-generic
Os: linux
BuildTime: 2017-01-10T23:09:49.630531934+00:00
ApiVersion: 1.24
Version: 1.12.6-cs6
GitCommit: 712e864
Arch: amd64
GoVersion: go1.6.4
Starting build of index.docker.io/liufanl/ssr-with-net-speeder-arukas:arukas...
Step 1 : FROM readytalk/nodejs

 ---> 483449fa72a9

Step 2 : WORKDIR /app

 ---> Running in 3068da104a7d

 ---> 8a6498a25caa

Removing intermediate container 3068da104a7d

Step 3 : WORKDIR /app/views

 ---> Running in 4ca8b19ae781

 ---> 9e1d6c513ac6

Removing intermediate container 4ca8b19ae781

Step 4 : WORKDIR /app/public

 ---> Running in 4c3578aa7018

 ---> 798137f32fea

Removing intermediate container 4c3578aa7018

Step 5 : COPY server.js /app/

 ---> 17665ddc386c

Removing intermediate container a46470304ef0

Step 6 : COPY package.json /app/

 ---> 6b304e615da5

Removing intermediate container 9f58d8fdbb8d

Step 7 : COPY index.html /app/views

 ---> b6871f9f3557

Removing intermediate container 77d82e8e2958

Step 8 : COPY css.css /app/public

 ---> 8b703df78581

Removing intermediate container b796408afbd0

Step 9 : RUN npm install

 ---> Running in 4ca725ac1b42

[91mnpm[0m
[91m WARN package.json arukas-get-ip-port@1.0.0 No description
[0m
[91mnpm WARN package.json arukas-get-ip-port@1.0.0 No repository field.
[0m
[91mnpm[0m
[91m WARN package.json arukas-get-ip-port@1.0.0 No README data
[0m
[91mnpm [0m
[91mWARN engine superagent@3.4.1: wanted: {"node":">= 0.12"} (current: {"node":"0.10.36","npm":"1.4.28"})
[0m
[91mnpm[0m
[91m [0m
[91mWARN engine form-data@2.1.2: wanted: {"node":">= 0.12"} (current: {"node":"0.10.36","npm":"1.4.28"})
[0m
ejs@2.5.5 ../node_modules/ejs

express@4.14.1 ../node_modules/express
├── escape-html@1.0.3
├── array-flatten@1.1.1
├── utils-merge@1.0.0
├── merge-descriptors@1.0.1
├── fresh@0.3.0
├── methods@1.1.2
├── cookie-signature@1.0.6
├── vary@1.1.0
├── path-to-regexp@0.1.7
├── encodeurl@1.0.1
├── range-parser@1.2.0
├── content-type@1.0.2
├── parseurl@1.3.1
├── etag@1.7.0
├── cookie@0.3.1
├── content-disposition@0.5.2
├── serve-static@1.11.2
├── depd@1.1.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.5.1 (unpipe@1.0.0, statuses@1.3.1)
├── qs@6.2.0
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.1.3 (forwarded@0.1.0, ipaddr.js@1.2.0)
├── send@0.14.2 (ms@0.7.2, destroy@1.0.4, statuses@1.3.1, mime@1.3.4, http-errors@1.5.1)
├── accepts@1.3.3 (negotiator@0.6.1, mime-types@2.1.14)
└── type-is@1.6.14 (media-typer@0.3.0, mime-types@2.1.14)

superagent@3.4.1 ../node_modules/superagent
├── component-emitter@1.2.1
├── methods@1.1.2
├── cookiejar@2.1.0
├── extend@3.0.0
├── mime@1.3.4
├── formidable@1.1.1
├── qs@6.3.0
├── debug@2.6.0 (ms@0.7.2)
├── readable-stream@2.2.2 (buffer-shims@1.0.0, process-nextick-args@1.0.7, util-deprecate@1.0.2, isarray@1.0.0, string_decoder@0.10.31, inherits@2.0.3, core-util-is@1.0.2)
└── form-data@2.1.2 (asynckit@0.4.0, combined-stream@1.0.5, mime-types@2.1.14)

 ---> 00a95a0a2483

Removing intermediate container 4ca725ac1b42

Successfully built 00a95a0a2483

Pushing index.docker.io/liufanl/ssr-with-net-speeder-arukas:arukas...
Done!
Build finished

**Comment by malaohu** [comment]
把你的镜像地址贴出来

**Comment by liufanl** [comment]
@malaohu liufanl/ssr-with-net-speeder-arukas

**Comment by malaohu** [comment]
你的镜像确实不行呢。
https://163.arukascloud.io/
